const specializations = [
  "Anestesiologista",
  "Angiologista",
  "Cardiologista",
  "Cirurgião Cardiovascular",
  "Cirurgião da Mão",
  "Cirurgião de Cabeça e Pescoço",
  "Cirurgião do Aparelho Digestivo",
  "Cirurgião Geral",
  "Cirurgião Pediátrico",
  "Cirurgião Plástico",
  "Cirurgião Torácico",
  "Cirurgião Vascular",
  "Clínico Geral",
  "Dermatologista",
  "Endocrinologista",
  "Endoscopista",
  "Gastroenterologista",
  "Geneticista",
  "Geriatra",
  "Ginecologista",
  "Hematologista",
  "Homeopata",
  "Infectologista",
  "Mastologista",
  "Médico do Trabalho",
  "Médico de Família e Comunidade",
  "Nefrologista",
  "Neurocirurgião",
  "Neurologista",
  "Nutrólogo",
  "Nutricionista",
  "Obstetra",
  "Oftalmologista",
  "Oncologista Clínico",
  "Ortopedista",
  "Otorrinolaringologista",
  "Pediatra",
  "Pneumologista",
  "Proctologista",
  "Psiquiatra",
  "Psicólogo(a)",
  "Reumatologista",
  "Sexólogo",
  "Urologista",
  "Fisiatra",
  "Fisioterapeuta",
  "Terapia Ocupacional",
  "Fonodiólogo(a)",
  "Médico Intensivista",
  "Médico Esportivo",
  "Médico Paliativista",
  "Outros",
  "Alergista/Imunologista"
];

export default specializations;